### ISSUE TITLE
Tool: group elements

### ISSUE THREAD

**Issue by FelipeDrytven** [infinyte7/image-occlusion-in-browser#2]
You are developing one of the most incredible tools for Android! I pray for your tool be integrated to AnkiDroid. :)

Have you taken a look at Anki Doodle? There may be something you can take advantage of, like the zoom control, the automatic transfer of cards to AnkiDroid... Your SVG filetype and your group elements are the most advantages over Anki Doodle (the development was stopped).

https://github.com/mmjang/Ankillusion
(If you want to download it, the apk is here: https://apkpure.com/anki-doodle/com.mmjang.ankillusion)

My friend, is there any way to help you? Unfortunately, I don't know programming.

**Comment by infinyte7** [comment]
I have viewed that one. The problem is that the app is only compatible with AnkiDroid. (For Anki there is addon but for AnkiMobile nothing). So, I have implemented the same thing to be used on desktop, ios and android.

```zoom```
I have improved the ```zoom``` feature in version 0.6.

For automatic adding, there need to code an app using AnkiDroid API. Also it take time for maintenance. And also I am beginners in Java. 
So may be you can ask https://github.com/david-allison-1 . He has already ported some desktop addon to AnkiDroid (e.g. MIA mass editor).

**Comment by FelipeDrytven** [comment]
Got it! Your proposal is really cool: democratize a resource for all Anki applications.

I imagine that soon David will integrate his application into the main app. Will 0.6 correct that bug in the rectangles that disappear when saving grouped cloze cards?

**Comment by infinyte7** [comment]
Have you tried that one? Yes, I have also improved that one.

**Comment by FelipeDrytven** [comment]
Great! I tried now! You really improved that. 😀
